name: Deploy compute.bicep to Azure

on:
  push:
    branches:
      - main  # or change to your target branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LINUX_VM_SECRET }}

      - name: Deploy compute.bicep
        uses: azure/cli@v1
        with:
          inlineScript: |
            az deployment group create \
              --resource-group MinecraftRG \
              --template-file infrastructure/compute.bicep

      - name: Deploy Bicep file
          run: |
            az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file ./main.bicep \
            --parameters adminUsername='MCAdmin' \
                   authenticationType='password' \
                   adminPasswordOrKey='${{ secrets.LINUX_VM_SECRET }}'



              az login --service-principal -u $project_sp_client_id -p $project_sp_secret_value --tenant $tenant_id

