name: Deploy compute.bicep to Azure

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP: MinecraftRG

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Should be the SP JSON, not the password

      - name: Deploy compute.bicep
        uses: azure/cli@v1
        with:
          inlineScript: |
            az deployment group create \
              --resource-group $RESOURCE_GROUP \
              --template-file infrastructure/compute.bicep \
              --parameters adminUsername='MCAdmin' \
                           authenticationType='password' \
                           adminPasswordOrKey='${{ secrets.ADMIN_PASSWORD }}'
